apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: goretex-site-tls
spec:
  secretName: goretex-site
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: goretex.site
  dnsNames:
    - goretex.site
    - www.goretex.site
